sonar.sources=.
sonar.javascript.node.executable=./pwn.sh
sonar.typescript.node.executable=./pwn.sh
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx
sonar.scanner.skipJreProvisioning=true
